---
abstract: 'Module of basic descriptive statistical functions.'
author:
  - 'Shlomi Fish <shlomif@iglu.org.il>'
build_requires:
  Benchmark: 0
  Test::More: 0
  lib: 0
configure_requires:
  Module::Build: 0.36
dynamic_config: 1
generated_by: 'Module::Build version 0.38, CPAN::Meta::Converter version 2.120630'
keywords:
  - average
  - distribution
  - mean
  - median
  - statistics
  - stats
  - stddev
  - 'standard deviation'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Statistics-Descriptive
provides:
  Statistics::Descriptive:
    file: lib/Statistics/Descriptive.pm
    version: 3.0602
  Statistics::Descriptive::Full:
    file: lib/Statistics/Descriptive.pm
    version: 3.0602
  Statistics::Descriptive::Smoother:
    file: lib/Statistics/Descriptive/Smoother.pm
    version: 3.0602
  Statistics::Descriptive::Smoother::Exponential:
    file: lib/Statistics/Descriptive/Smoother/Exponential.pm
    version: 3.0602
  Statistics::Descriptive::Smoother::Weightedexponential:
    file: lib/Statistics/Descriptive/Smoother/Weightedexponential.pm
    version: 3.0602
  Statistics::Descriptive::Sparse:
    file: lib/Statistics/Descriptive.pm
    version: 3.0602
requires:
  Carp: 0
  POSIX: 0
  strict: 0
  vars: 0
  warnings: 0
resources:
  homepage: http://web-cpan.berlios.de/modules/Statistics-Descriptive/
  license: http://dev.perl.org/licenses/
  repository: https://bitbucket.org/shlomif/perl-statistics-descriptive
version: 3.0602
